// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RainbowStatsAPI;

namespace RainbowStatsAPI.Migrations
{
    [DbContext(typeof(RainbowStatsContext))]
    partial class RainbowStatsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("OperatorWeapon", b =>
                {
                    b.Property<string>("OperatorsName")
                        .HasColumnType("text");

                    b.Property<string>("WeaponsName")
                        .HasColumnType("text");

                    b.HasKey("OperatorsName", "WeaponsName");

                    b.HasIndex("WeaponsName");

                    b.ToTable("OperatorWeapon");
                });

            modelBuilder.Entity("RainbowStatsAPI.Models.Operator", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("RainbowStatsAPI.Models.Weapon", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<int>("Rpm")
                        .HasColumnType("integer");

                    b.Property<string>("SerializedDamageRanges")
                        .HasColumnType("text");

                    b.Property<string>("Slot")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("OperatorWeapon", b =>
                {
                    b.HasOne("RainbowStatsAPI.Models.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RainbowStatsAPI.Models.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponsName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
